# site info
author: Daniel Duckworth
url: http://www.transmogrifier.com

# # use pandoc for rendering
markdown: pandoc
pandoc:
  extensions: [smart, mathjax]

# enable syntax coloring via pygments
pygments: true

# URL for blog posts
permalink: /blog/:title.html

# automatically update when running server
# auto: true

# don't deploy these folders/files
exclude: [Gemfile, Gemfile.lock, README]
